swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <body class="swagger-section">
      <div id='header'>
            <div class="swagger-ui-wrap">
              <a id="logo" href="http://swagger.io"><img class="logo__img" alt="swagger" height="30" width="30" src="images/logo_small.png" /><span class="logo__title">swagger</span></a>
              <!-- Bootstrap Simple Sidebar: Toggle button -->
              <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
              <form id='api_selector'>
                <div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text"/></div>
                <div id='auth_container'></div>
                <div class='input'><a id="explore" class="header__btn" href="#" data-sw-translate>Explore</a></div>
              </form>
            </div>
          </div>
      <!-- Bootstrap Simple Sidebar: Global wrapper, contains sidebar and page -->
      <div id="wrapper">
        <!-- Bootstrap Simple Sidebar: Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                </li>
                <li>
                    <a href="#">Shortcuts</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
      </body>
        
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: |
            <form>
            <div>
                <img onerror=alert('aaaaaaaa') src=1>
               
            </div>
            </form>
            
            <form>
            <div id="content">
                <script type="text/javascript">
                    function myFunction() {
                      debugger;
                      alert('ddddddd') 
                      console.log('yyyyy') 
                    }
                    myFunction();
                </script>
            </div>
            </form>
            
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('nnnnnnnnnnnnn') src=1>"></form>
      tags:
        - accounts
      operationId: findAccounts
      summary: |
            <form>
            <div>
                <img onerror=alert('aaaaaaaa') src=1>
               
            </div>
            </form>
            
            <form>
            <div id="content">
                <script type="text/javascript">
                    function myFunction() {
                      alert('ddddddd') 
                      console.log('yyyyy') 
                    }
                    myFunction();
                </script>
            </div>
            </form>
            
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('nnnnnnnnnnnnn') src=1>"></form>
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
              format: int64
              in: path
              name: id
              required: true
              type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findGroupsById
      summary: Finds groups by id
    post:
      parameters:
        - description: Id value to filter by
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You cannot create an LDAP group with a POST.  '
      operationId: createGroupById
      summary: Creates a new group by id
    put:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: You cannot change information for an LDAP group with a PUT.
      operationId: updateGroupById
      summary: Updates an existing group by id
 
  